version: '3'
services:
  sqlserver:
    container_name: 'sql_server_data_panel'
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: dataPanel!@#
    ports:
      - '1434:1433'
    expose:
      - '1434'
            
    